repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        types: [python]
        args: [
            '--profile=black',
            '--line-length=99',
            '--trailing-comma',
            '--use-parentheses',
            '--ensure-newline-before-comments',
        ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
